name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22.x (Current)
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install dependencies (clean)
        run: pnpm install --frozen-lockfile

      - name: Lint (JS/Vue)
        run: pnpm run lint --max-warnings=0

      - name: Security audit (non-blocking)
        run: pnpm audit --audit-level=moderate || true

      - name: Build project
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Upload production artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: getty-build
          path: |
            public/
            admin-frontend/dist/
          if-no-files-found: warn

      - name: Show i18n runtime hash
        run: |
          grep -o "version:'[a-z0-9]\+'" public/js/min/i18n-runtime.js || true
