name: Node CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Use npm ci when lockfile is present
        if: hashFiles('package-lock.json') != ''
        run: npm ci

      - name: Fallback to npm install when lockfile is absent
        if: hashFiles('package-lock.json') == ''
        run: npm install

      - name: Lint CSS (stylelint)
        if: hashFiles('.stylelintrc*') != '' && matrix.node-version == '22.x'
        run: |
          npx stylelint "src/**/*.css"

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Security audit (production only)
        if: matrix.node-version == '22.x'
        continue-on-error: true
        run: npm audit --omit=dev --audit-level=high

      - name: Upload built public assets (manual runs only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: public-${{ matrix.node-version }}
          path: public
          if-no-files-found: warn
